---
name: Deploy as GitHub page
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch to checkout
        default: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: "lame-incremental-text-adventure/lita"
          ref: ${{ inputs.branch }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install dependencies
        shell: bash
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk
      
      - name: Build for wasm
        shell: bash
        run: trunk build --release
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
